application: reformasky01
version: 1
runtime: python27

api_version: 1
threadsafe: true

handlers:
- url: /.*
<<<<<<< HEAD
  script: problem3.application
=======
  script: reformasky01.application
>>>>>>> cd78c30cc7d40a80d517ec9bb2eeb14e96548e88


libraries:
- name: jinja2
  version: latest